version: "3.8"

services:
  mysql-server:
    container_name: zoo-mysql-server
    image: mysql:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${ZOO_DB_ROOT_PASSWORD}
    volumes:
      - zoo-mysql-server:/var/lib/mysql
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}

  zoo-store:
    depends_on:
      - mysql-server
    build: ../Zoo-Store-master
    restart: on-failure
    env_file: ./.env
    ports:
      - "1234:8081"
    environment:
      SPRING_APPLICATION_JSON: '{
           "spring.datasource.url"  : "jdbc:mysql://mysql-server:${MYSQLDB_DOCKER_PORT}/${ZOOSTORE_DB_DATABASE}?useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC&allowPublicKeyRetrieval=true",
           "spring.datasource.username" : "${ZOO_DB_USER}",
           "spring.datasource.password" : "${ZOO_DB_ROOT_PASSWORD}",
           "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
           "spring.jpa.hibernate.ddl-auto" : "update"
         }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true


  item-storage:
    depends_on:
      - mysql-server
      - zoo-store
    build: ../Item-Storage
    restart: on-failure
    env_file: ./.env
    ports:
      - "1235:8082"
    environment:
      SPRING_APPLICATION_JSON: '{
           "spring.datasource.url"  : "jdbc:mysql://mysql-server:${MYSQLDB_DOCKER_PORT}/${STORAGE_DB_DATABASE}?useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC&allowPublicKeyRetrieval=true",
           "spring.datasource.username" : "${ZOO_DB_USER}",
           "spring.datasource.password" : "${ZOO_DB_ROOT_PASSWORD}",
           "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
           "spring.jpa.hibernate.ddl-auto" : "update"
         }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

  zoo-bff:
    depends_on:
      - mysql-server
      - zoo-store
      - item-storage
    build: ../BFF-ZooStore-ItemStorage
    restart: on-failure
    env_file: ./.env
    ports:
      - "1236:8083"
    environment:
      SPRING_APPLICATION_JSON: '{
           "spring.datasource.url"  : "jdbc:mysql://mysql-server:${MYSQLDB_DOCKER_PORT}/${BFF_DB_DATABASE}?useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC&allowPublicKeyRetrieval=true",
           "spring.datasource.username" : "${ZOO_DB_USER}",
           "spring.datasource.password" : "${ZOO_DB_ROOT_PASSWORD}",
           "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
           "spring.jpa.hibernate.ddl-auto" : "update"
         }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  zoo-mysql-server: